server:
  port: 80

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进EurekaServer,默认为true
    service-url:
      #      defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版

#设置feign客户端超时时间
feign:
  client:
    config:
      default:
        readTimeout: 5000 # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
        connectTimeout: 5000 # 指的是建立连接后从服务器读取到可用资源所用的时间

logging:
  level:
    com.yewen.springcloud.service.PaymentFeignService: debug # feign日志以什么级别监控那个接口
