server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.223.50
#        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"